### ISSUE TITLE
p_td_d and p_tw_d are of suspiciously similar construction

### ISSUE THREAD

**Issue by jnothman** [martingerlach/hSBM_Topicmodel#5]
`n_db` and `n_dbw` are initially populated identically:
https://github.com/martingerlach/hSBM_Topicmodel/blob/2ba7658ac513b10d9bc2b1c2a63dd6512449e7ca/sbmtm.py#L397-L406

They are then indexed by [`ind_d`](https://github.com/martingerlach/hSBM_Topicmodel/blob/2ba7658ac513b10d9bc2b1c2a63dd6512449e7ca/sbmtm.py#L410-L412) and [`ind_w2`](https://github.com/martingerlach/hSBM_Topicmodel/blob/2ba7658ac513b10d9bc2b1c2a63dd6512449e7ca/sbmtm.py#L418-L419) respectively. But `ind_d` and `ind_w2` are constructed identically also, before these matrices are normalised into probabilities.

Are these not meant to be distinct outputs?

**Comment by martingerlach** [comment]
Yes, the two are constructed very similarly - but the output of p_td_d and p_tw_d will be different. In fact, the shape of the two matrices is different: shape(p_td_d) = B_d x D  and shape (p_tw_d) = B_w x D, where D is the number of documents and B_d is the number of groups for document-nodes and B_w is the number of groups for word-nodes (we are clustering a bipartite network, such that the total number of groups/communities in the network is B = B_d + B_w).

The two matrices thus count two different things:
- p_td_d counts the number of edges (tokens) in document d that connect to a doc-group
- p_tw_d couns the number of edges (tokens) in document d that connect to a word-group.

In the code above the loop iterates over all edges (e). Each edge is a connection between a document-node (v1) and a word-node (v2). These two nodes will belong to different groups, i.e. the document-nodes will belong to a document-group (z1) and the word-node will belong to a word-group (z2). However, z1 will have only values from 1,2,..,B_d and z2 will have values from B_d+1, B_d+2,...,B_d+B_w (v1 will go from 1,2,...,D).
Even though we initialize n_db and n_dbw as arrays of shape D x B, we then remove columns in which there are no counts (we sum over all rows and only keep those columns in which the count is larger than 0):
ind_d = np.where(np.sum(n_db,axis=0)>0)[0]
ind_w2 = np.where(np.sum(n_dbw,axis=0)>0)[0]

Since the two arrays are populated with values of z1 and z2, respectively, we will end up with different arrays. 

For the non-overlapping block model that is implemented in the code, a document d belongs to one and only one document-group. Therefore p_td_d contains only 0s and 1s (in fact, each column only has a single entry as 1 and the rest is 0's). In contrast, the p_tw_d counts the edges of a document in relation to the wod-groups, which usually shows overlap, leading to values between 0 and 1.


I hope this clarifies.

**Comment by jnothman** [comment]
Ahh... I didn't see the `-D` there and suspect that disappeared somewhere in the port (not sure when??) Sorry for the noise. Trying to hurry things before we close shop for the year.
